pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'street-runner:$(build.buildId)'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'RevlucioAzureSubscription'
    azureContainerRegistry: revlucio.azurecr.io
    command: login
- bash: |
   docker build -t revlucio.azurecr.io/street-runner:$(Build.BuildId) .
   docker push revlucio.azurecr.io/street-runner:$(Build.BuildId) 
   displayName: 'Build, tag and push image'