pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'street-runner:$(build.buildId)'

steps:
#- script: docker build -f Dockerfile -t $(imageName) .
#  displayName: 'docker build'
#- script: docker push $(imageName) 

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'revlucio.azurecr.io/repositoryname:$(Build.BuildId)'
#- task: Docker@1
#  displayName: Login
#  inputs:
#    azureSubscriptionEndpoint: 'ContosoAzureSubscription'
#    azureContainerRegistry: revlucio.azurecr.io
#    command: login
#- task: Docker@1
#  displayName: 'Push an image'
#  inputs:
#    command: 'push'
#    imageName: 'revlucio.azurecr.io/repositoryname:$(Build.BuildId)'